### PR TITLE
Update fr.free.Homebank.json

### PR DESCRIPTION
**Pull request by alexpattyn**
Updated to v5.4.2

### CODE REVIEW

**Comment by alexpattyn** [comment]
Reference issue: https://github.com/flathub/fr.free.Homebank/issues/7

**Comment by alexpattyn** [comment]
v5.4 seems to be a major release, but didn't see anything breaking in the change log.

**Comment by alexpattyn** [comment]
Tested latest build and it seems to work just fine. Just need someone to merge the change.

**Comment by bilelmoussaoui** [comment]
> Tested latest build and it seems to work just fine. Just need someone to merge the change.

I will trust you on that. It seems to run without any issues but I haven't tested any functionalities

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
