### PR TITLE
Bump homebank version to 5.5.4

### PR DESCRIPTION
**Pull request by unholyeyebrows**
This is my first pull request to please accept my apologies for any errors.

### CODE REVIEW

**Comment by unholyeyebrows** [comment]
I've just installed the test build and it opens fine and confirmed the version is now 5.5.4.

**Comment by unholyeyebrows** [comment]
Just a further thought to help my learning - my original build failed due to the incorrect sha256 checksum as follows:

Failed to download sources: module homebank: Wrong sha256 checksum for homebank-5.5.4.tar.gz, expected "1c753807d6ec40fcfcf4a3937d61fc3e797c7e2d68f2094f22bb663c91115252", was "0d0669bca099340ae5c213ea13cb2b93283bfc8a0e4cf7a5902c1829366e5765"

I adjusted my pull request to reflect this and the flatpak has then built successfully. However I am confused as to why the checksum was flagged as incorrect since when I calculate it manually I get:

sha256sum homebank-5.5.4.tar.gz 
1c753807d6ec40fcfcf4a3937d61fc3e797c7e2d68f2094f22bb663c91115252  homebank-5.5.4.tar.gz

For future reference I would like to know how to get the sha256 right first time, or does this mean the .tar.gz the flatpak builder downloaded is somehow different to the one I have downloaded from the Homebank web site?

**Comment by hfiguiere** [comment]
Either I download the tarball and run `sha256sum` on it, or I just let flatpak-builder tell me what it is expecting as I try to build locally. Of course if upstream provide them it's easier.

**Comment by Swissbite** [comment]
Would like to see this PR merged and have an up-to-date version on flathub

**Comment by unholyeyebrows** [comment]
Is there any chance of getting this PR merged? Perhaps this flatpak isn't actively maintained currently? Thanks.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
now it uses a deprecated runtime.

**Comment by hfiguiere** [comment]
I have submitted #17 to include this on top of the runtime update/

**Comment by hfiguiere** [comment]
integrated this with #17 and then ended up updating to 5.5.5. Should be available in a few of hours.

bonus point it should properly show the version now on flathub.

**Pull request closed without merging**
