### PR TITLE
Bump versions and runtime, remove patch

### PR DESCRIPTION
**Pull request by idunno101**

### CODE REVIEW

**Comment by alexpattyn** [comment]
bot build

**Comment by alexpattyn** [comment]
Hey @idunno101 would you be able to bump this to v5.5? Then once that is working hopefully we can ping one of the maintainers for a merge.

**Comment by fedelibre** [comment]
Attached patch bumps it to v5.5:
[0001-Update-to-version-5.5.patch.txt](https://github.com/flathub/fr.free.Homebank/files/6058121/0001-Update-to-version-5.5.patch.txt)

flatpak is not aware of the Homebank version because appdata file is missing release tag:

```
$ grep release /app/share/appdata/fr.free.Homebank.appdata.xml

```

This should be fixed upstream of course.

**Comment by alexpattyn** [comment]
@bilelmoussaoui Would I be able to get the permissions to edit this PR and call bot build? v5.5.1 released and there is the new gnome runtime as well. I didn't want to just make a new PR and copy what @idunno101 did.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Would I be able to get the permissions to edit this PR and call bot build? v5.5.1 released and there is the new gnome runtime as well. I didn't want to just make a new PR and copy what @idunno101 did.

Please submit a new PR instead, and we can close this one once yours is merged.

**Comment by alexpattyn** [comment]
Will do!

**Comment by bilelmoussaoui** [comment]
Superseded by #13

**Pull request closed without merging**
